# Generated by Django 5.0.1 on 2024-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0002_book_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
