# Generated by Django 5.0.1 on 2024-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0004_vehicle_available_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
                ('Vehicle_id', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
