# Generated by Django 5.0.1 on 2024-03-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0006_remove_vehicle_available_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
    ]
