# Generated by Django 5.0.1 on 2024-03-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0010_remove_payment_timestamp_book_user_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
