# Generated by Django 5.0.1 on 2024-03-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0011_remove_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
